person:
  age: 50
  boss: false
  birthday: 2017/10/01
  map: {person1: JK,person2: Tom}
  dog:
    name: wangcai
    sex: fale
  list:
    - xiaoming
    - xiaohua
    - xiaoye

config:
  index: 10


